### ISSUE TITLE
Request to add new exchanges

### ISSUE THREAD

**Issue by Dedinvest** [aneonex/BitcoinChecker#221]
Hi, first of all, your app is great, thank you very much! It would be awesome if you could add YouHodler and Nexo in your database! Thanks again

**Comment by aneonex** [comment]
Thanks for using the app.

Regarding the new exchanges (YouHodler and Nexo).
Unfortunately, I could not find any information about these exchanges provide a public API. This will not allow them to be added, because the app receives price information directly from exchanges through the API.

Let me know if you have more information.
